import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def plot_bisecting_intercluster_space(X_final_preprocessed, bisect_kmeans_final, final_labels, sample_size=20000):
    """
    Renders a custom Intercluster Projection Space and Density Map for Bisecting K-Means
    by plotting background sample density along PC1/PC2 and overlaying annotated centroids.
    """
    print(f"\n--- Generating Custom Bisecting Intercluster Space Projection (N={sample_size}) ---")
    
    # 1. Extract the coordinates of the 4 definitive centroids generated by Bisecting K-Means
    # We take the first two columns, corresponding to PC1 and PC2
    bisect_centroids = bisect_kmeans_final.cluster_centers_[:, :2]

    # 2. Create a temporary DataFrame from the full PCA matrix for plotting the background density
    df_pca_plot = pd.DataFrame(X_final_preprocessed[:, :2], columns=['PC1', 'PC2'])
    df_pca_plot['Cluster'] = final_labels 

    # 3. Render the custom Intercluster Space and Density Map
    plt.figure(figsize=(10, 8))

    # Plot the background pixel density for each cluster
    sns.scatterplot(
        x='PC1', y='PC2', hue='Cluster', data=df_pca_plot.sample(sample_size, random_state=42),
        palette='Set1', alpha=0.3, s=2, edgecolor=None, legend='full'
    )

    # Overlay the definitive Bisecting K-Means centroids as large, prominent markers
    plt.scatter(
        bisect_centroids[:, 0], bisect_centroids[:, 1],
        color='black', marker='X', s=250, edgecolor='white', linewidth=2, label='Centroids'
    )

    # Annotate each centroid with its respective Cluster ID
    for i, (x, y) in enumerate(bisect_centroids):
        plt.text(
            x, y + 0.15, f"Cluster {i}",
            color='black', fontsize=11, fontweight='bold',
            ha='center', va='center',
            bbox=dict(boxstyle='round,pad=0.2', fc='white', alpha=0.7, ec='black', lw=0.5)
        )

    plt.title("Custom Intercluster Projection Space for Bisecting K-Means (K=4)", fontsize=12, fontweight='bold', pad=15)
    plt.xlabel("Principal Component 1 (PC1)")
    plt.ylabel("Principal Component 2 (PC2)")
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()