import time
import numpy as np
import pandas as pd
from sklearn.cluster import BisectingKMeans
from sklearn.metrics import davies_bouldin_score, calinski_harabasz_score
from scipy.spatial.distance import cdist

def fit_definitive_bisecting_kmeans(X_final_preprocessed, n_clusters=4):
    """
    Trains the definitive Bisecting K-Means model on the full orthogonal PCA matrix,
    manually reconstructs the global SSE (Inertia) via centroid distance tracking,
    and prints out the structural validation metrics.
    """
    print(f"Training the definitive Bisecting K-Means model on the PCA preprocessed dataset (K={n_clusters})...")
    start_time = time.time()

    # Initialize BisectingKMeans using target clusters and k-means++ for internal splits
    bisect_kmeans_final = BisectingKMeans(
        n_clusters=n_clusters,
        init='k-means++',
        n_init=10,
        random_state=42
    )

    # Fit and predict directly on the orthogonal PCA components matrix
    final_labels = bisect_kmeans_final.fit_predict(X_final_preprocessed)

    elapsed = time.time() - start_time
    print(f"Bisecting K-Means training completed successfully in {elapsed:.1f} seconds.")
    
    # Ensure cluster labels are structured as a standard NumPy integer array for indexing
    labels_array = np.asarray(final_labels, dtype=int)

    # ==============================================================================
    # 1. MATHEMATICAL METRICS EVALUATION (FULL PCA FEATURE SPACE)
    # ==============================================================================

    # Extract the definitive centroids generated by the Bisecting K-Means model
    centroids = bisect_kmeans_final.cluster_centers_

    # Compute the comprehensive pairwise Euclidean distance matrix between all samples and all centroids
    distances_to_all_centroids = cdist(X_final_preprocessed, centroids, metric='euclidean')

    # Filter out only the distance connecting each specific pixel to its formally assigned cluster
    distances_to_assigned = distances_to_all_centroids[np.arange(len(labels_array)), labels_array]

    # Compute the final Sum of Squared Errors (SSE / Inertia)
    bisect_sse = np.sum(distances_to_assigned ** 2)

    # Calculate standard academic clustering validation indices
    bisect_db = davies_bouldin_score(X_final_preprocessed, labels_array)
    bisect_ch = calinski_harabasz_score(X_final_preprocessed, labels_array)

    # Print out the structural evaluation dashboard
    print("\n======= BISECTING K-MEANS MODEL METRICS (K=4) =======")
    print(f"SSE (Inertia): {bisect_sse:.2f}")
    print(f"Davies-Bouldin Index: {bisect_db:.4f}")
    print(f"Calinski-Harabasz Index: {bisect_ch:.2f}")
    print("=====================================================\n")
    
    return bisect_kmeans_final, final_labels